In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = sns.load_dataset("diamonds")

In [3]:
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [4]:
df.shape

(53940, 10)

In [5]:
df.dtypes

carat       float64
cut        category
color      category
clarity    category
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB

In [7]:
df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [8]:
df.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [9]:
df.duplicated().sum()

146

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
(df[["x", "y", "z"]] == 0).sum()

x     7
y     6
z    19
dtype: int64

In [12]:
df = df[(df["x"] > 0) & (df["y"] > 0) & (df["z"] > 0)]

In [ ]:
# Fonction pour détecter et remplacer les valeurs aberrantes avec les Bounds
def replace_outliers(df):
    for col in df.select_dtypes(include=['number']).columns: 
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        df[col] = np.where(df[col] < lower_bound, lower_bound, df[col])
        df[col] = np.where(df[col] > upper_bound, upper_bound,df[col])

In [ ]:
df["volume"] = df["x"] * df["y"] * df["z"] # volume approximatif

In [ ]:
df["price_per_carat"] = df["price"] / df["carat"] # prix par piods (carat)

In [17]:
df.describe()

,carat,depth,table,price,x,y,z,volume,price_per_carat
count,53775.000000,53775.000000,53775.000000,53775.000000,53775.000000,53775.000000,53775.000000,53775.000000,53775.000000
mean,0.797536,61.748232,57.457806,3931.220288,5.731579,5.734909,3.539964,129.872846,4009.181301
std,0.473169,1.429639,2.233257,3985.918716,1.118611,1.139451,0.702017,78.136513,2013.043394
min,0.200000,43.000000,43.000000,326.000000,3.730000,3.680000,1.070000,31.707984,1051.162791
25%,0.400000,61.000000,56.000000,951.000000,4.710000,4.720000,2.910000,65.214611,2478.431373
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000,114.852720,3496.250000
75%,1.040000,62.500000,59.000000,5324.000000,6.540000,6.540000,4.030000,170.839422,4950.000000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000,3840.598060,17828.846154

In [18]:
df.to_csv("diamonds_clean.csv", index=False)